[2018-04-15 13:06:58,059] [INFO] hello
[2018-04-15 13:07:57,996] [INFO] wechatConfirm
[2018-04-15 13:07:58,000] [ERROR] Internal Server Error: /wechat
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/pi/github/RaspberryPi/Django/WeChat/WeChat/wechatInterface.py", line 38, in wechat_main
    confirmResult=wechatConfirm(request)
  File "/home/pi/github/RaspberryPi/Django/WeChat/WeChat/wechatInterface.py", line 73, in wechatConfirm
    hashlist.sort()
TypeError: unorderable types: NoneType() < str()
[2018-04-15 13:08:14,303] [INFO] wechatConfirm
[2018-04-15 13:10:54,587] [INFO] hello
[2018-04-15 13:11:12,461] [INFO] 1
[2018-04-15 13:11:12,463] [ERROR] Internal Server Error: /wechat
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/pi/github/RaspberryPi/Django/WeChat/WeChat/wechatInterface.py", line 51, in wechat_main
    orderProcesser=OrderProcesser()
  File "/home/pi/github/RaspberryPi/Django/WeChat/WeChat/orderProcesser.py", line 28, in processOrder
    humidifier=Humidifier.Humidifier()
  File "/home/pi/github/RaspberryPi/Django/WeChat/WeChat/Humidifier.py", line 15, in __init__
    GPIO.setup(12,GPIO.OUT)
RuntimeError: No access to /dev/mem.  Try running as root!
[2018-04-15 13:42:33,293] [INFO] 1
[2018-04-15 13:42:33,295] [ERROR] Internal Server Error: /wechat
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/pi/github/RaspberryPi/Django/WeChat/WeChat/wechatInterface.py", line 51, in wechat_main
    replyResult=msgProcesser.genMsg(replyMsg)
  File "/home/pi/github/RaspberryPi/Django/WeChat/WeChat/orderProcesser.py", line 28, in processOrder
    humidifier=Humidifier.Humidifier()
  File "/home/pi/github/RaspberryPi/Django/WeChat/WeChat/Humidifier.py", line 15, in __init__
    GPIO.setup(12,GPIO.OUT)
RuntimeError: No access to /dev/mem.  Try running as root!
[2018-04-15 13:42:49,294] [INFO] 1
[2018-04-15 13:43:26,438] [INFO] 开加湿
[2018-04-15 13:43:34,078] [INFO] 关加湿
[2018-04-15 13:43:38,193] [INFO] 温度
[2018-04-15 13:43:42,656] [INFO] 湿度
[2018-04-15 13:44:08,027] [INFO] 温度
[2018-04-15 13:51:55,449] [INFO] 开加湿
[2018-04-15 13:52:00,389] [INFO] 关加湿
[2018-04-15 13:52:04,788] [INFO] 温度
[2018-04-15 13:52:08,852] [INFO] 湿度
[2018-04-15 13:54:39,243] [INFO] 温度
[2018-04-15 13:54:43,175] [INFO] 温度
[2018-04-15 13:54:55,703] [INFO] 湿度
[2018-04-15 13:55:02,760] [INFO] 关加湿
